name: deploy-infra

on:
  push:
    paths:
      - 'infra/**'
  workflow_dispatch: {}

env:
  RESOURCE_GROUP_DEV: aguadamillas_students_1
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: panchomb

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep code 
    - name: Run Bicep linter
      run: az bicep build --file ./infra/main.bicep

  deploy:
#   if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:

      # Checkout code
    - uses: actions/checkout@main
    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./infra/main.bicep
        parameters: ./infra/parameters/parameters.json
        deploymentName: ${{ env.USER_ALIAS }}
        failOnStdErr: false

    - name: Capture output
      id: capture_output
      run: echo "BICEP_NAME_OUTPUT=$(az deployment group show --name ${{ env.USER_ALIAS }} --resource-group ${{ env.RESOURCE_GROUP_DEV }} --query 'properties.outputs.name' --output tsv)"
      
    - name: Display output
      run: echo "Output Name: ${{ steps.capture_output.outputs.BICEP_NAME_OUTPUT }}