name: deploy-app

on:
  push:
    paths:
      - 'app/**'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: panchombacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - working-directory: ./app
        run: |
          docker build . -t panchombacr.azurecr.io/flask-app-demo:${{ github.sha }}
          docker push panchombacr.azurecr.io/flask-app-demo:${{ github.sha }} 

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'node-rnc'
          images: 'panchombacr.azurecr.io/flask-app-demo:${{ github.sha }}'