name: deploy-app

on:
  push:
    paths:
      - 'app/**'
  workflow_dispatch: {}

env:
  REGISTRY_USERNAME: panchombacr
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  IMAGE_NAME: flask-app
  IMAGE_VERSION: latest
  AZURE_WEBAPP_NAME: panchomb-app

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: panchombacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set image version
        id: image-version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/})-$(date +'%Y.%m.%d.%H.%M')"

      - name: 'Build and push Docker image'
        working-directory: ./app
        run: |
          docker build . -t ${{ env.REGISTRY_USERNAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.image-version.outputs.version }}
          docker build . -t ${{ env.REGISTRY_USERNAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-latest
          docker push ${{ env.REGISTRY_USERNAME }}.azurecr.io/${{env.IMAGE_NAME}}:${{ steps.image-version.outputs.version }}
          docker push ${{ env.REGISTRY_USERNAME }}.azurecr.io/${{env.IMAGE_NAME}}:${{ github.ref_name }}-latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: '${{ env.REGISTRY_USERNAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-latest